remote_theme: pmarsceill/just-the-docs

title: ami-preservation
description: NYPL audio and moving image preservation documentation
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://nypl.github.io/ami-preservation/" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]