remote_theme: just-the-docs/just-the-docs

search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
color_scheme: "dark"

ga_tracking: G-Q1S5B27X4S
ga_tracking_anonymize_ip: true
